
export const ADD_AUCTION_REQUEST="ADD_AUCTION_REQUEST"
export const ADD_AUCTION_SUCCESS="ADD_AUCTION_SUCCESS"
export const ADD_AUCTION_FAIL="ADD_AUCTION_FAIL"

export const GET_AUCTION_REQUEST="GET_AUCTION_REQUEST"
export const GET_AUCTION_SUCCESS="GET_AUCTION_SUCCESS"
export const GET_AUCTION_FAIL="GET_AUCTION_FAIL"


export const GET_AUCTIONS_REQUEST="GET_AUCTIONS_REQUEST"
export const GET_AUCTIONS_SUCCESS="GET_AUCTIONS_SUCCESS"
export const GET_AUCTIONS_FAIL="GET_AUCTIONS_FAIL"

export const UPDATE_AUCTION_REQUEST="UPDATE_AUCTION_REQUEST"
export const UPDATE_AUCTION_SUCCESS="UPDATE_AUCTION_SUCCESS"
export const UPDATE_AUCTION_FAIL="UPDATE_AUCTION_FAIL"

export const DELETE_AUCTION_REQUEST="DELETE_AUCTION_REQUEST"
export const DELETE_AUCTION_SUCCESS="DELETE_AUCTION_SUCCESS"
export const DELETE_AUCTION_FAIL="DELETE_AUCTION_FAIL"



export const DELETE_AUCTION_RESET="DELETE_AUCTION_RESET"


