
export const ADD_LOT_REQUEST="ADD_LOT_REQUEST"
export const ADD_LOT_SUCCESS="ADD_LOT_SUCCESS"
export const ADD_LOT_FAIL="ADD_LOT_FAIL"


export const UPDATE_LOT_REQUEST="UPDATE_LOT_REQUEST"
export const UPDATE_LOT_SUCCESS="UPDATE_LOT_SUCCESS"
export const UPDATE_LOT_FAIL="UPDATE_LOT_FAIL"
export const UPDATE_LOT_RESET="UPDATE_LOT_RESET"

export const DELETE_LOT_REQUEST="DELETE_LOT_REQUEST"
export const DELETE_LOT_SUCCESS="DELETE_LOT_SUCCESS"
export const DELETE_LOT_FAIL="DELETE_LOT_FAIL"
export const DELETE_LOT_RESET="DELETE_LOT_RESET"

export const GET_LOT_REQUEST="GET_LOT_REQUEST"
export const GET_LOT_SUCCESS="DET_LOT_SUCCESS"
export const GET_LOT_FAIL="GET_LOT_FAIL"

export const GET_LOTS_REQUEST="GET_LOTS_REQUEST"
export const GET_LOTS_SUCCESS="DET_LOTS_SUCCESS"
export const GET_LOTS_FAIL="GET_LOTS_FAIL"



